### Crear un nuevo producto
POST https://api-bakery-production.up.railway.app/productos
Content-Type: application/json

{
  "nombre": "Pan de chocolate",
  "precio": 4.5,
  "descripcion": "Pan relleno con chocolate oscuro"
}

### Obtener todos los productos
GET https://api-bakery-production.up.railway.app/productos
